### ISSUE TITLE
no option for sound with webms

### ISSUE THREAD

**Issue by DanielFGray** [DanielFGray/yaxg#4]

**Comment by warmwaffles** [comment]
I use this lib, but I found this link and I am thinking about making a PR to add the option for sound

https://www.reddit.com/r/linux/comments/8n3ylp/screen_recording_in_x11_with_ffmpeg/

**Comment by DanielFGray** [comment]
I added this branch, test it out for me and let me know how it works?
https://github.com/DanielFGray/yaxg/tree/audio

**Comment by warmwaffles** [comment]
Yea it works great. It actually picks up my mic on my head set as well as desktop audio. :+1:
